"""empty message

Revision ID: 26dd97c6e4d3
Revises: 9d8055fef4e0
Create Date: 2024-09-24 20:31:29.617810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd97c6e4d3'
down_revision = '9d8055fef4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('duedate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('duedate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
