"""empty message

Revision ID: 9c51b39e079d
Revises: 570e3c7e7104
Create Date: 2025-09-27 14:21:40.347108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c51b39e079d'
down_revision = '570e3c7e7104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
